inhibit_all_warnings!
platform:ios,"9.0"

use_frameworks!

flutter_application_path = '../flutter_router_demo'

framework_dir = flutter_application_path + '/.ios/Flutter/App.framework'

if !File.exist?(framework_dir)
raise "App.framework 不存在， 请使用终端 进入 工程 flutter_router_demo 目录，运行 'flutter run'"
end

load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FluttterRouterDemo' do
  
    pod 'AFNetworking',  '~> 3.1.0'
    
    pod 'FlutterApp', :path => flutter_application_path
    
    install_flutter_engine_pod
    install_flutter_plugin_pods flutter_application_path
end

